{
 "title": "GPU Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip_port",
    "query": "SHOW TAG VALUES FROM gpu_ip_info WITH KEY = \"ip_port\" "
   }
  ]
 },
 "panels": [
  {
   "title": "loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "entropy loss",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "query": "SELECT mean(\"entropy_cost\") FROM \"autogen\".\"gpu_ip_info\" WHERE $timeFilter GROUP BY time(2m) fill(null)",
     "select": [
      [
       { "params": [ "entropy_cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total loss",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "query": "SELECT mean(\"entropy_cost\") FROM \"autogen\".\"gpu_ip_info\" WHERE $timeFilter GROUP BY time(2m) fill(null)",
     "select": [
      [
       { "params": [ "total_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "value loss",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "query": "SELECT mean(\"value_cost\") FROM \"autogen\".\"gpu_ip_info\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value_cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "policy loss",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "query": "SELECT mean(\"value_cost\") FROM \"autogen\".\"gpu_ip_info\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "policy_cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "样本消耗/样本生成",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "consumption_rate $tag_ip_port",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "ip_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "query": "SELECT mean(\"sample_consumption_rate\") FROM \"autogen\".\"gpu_ip_info\" WHERE (\"ip_port\" =~ /^$ip_port$/) AND $timeFilter GROUP BY time(5m), \"ip_port\" fill(null)",
     "select": [
      [
       { "params": [ "sample_consumption_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip_port", "operator": "=~", "value": "/^$ip_port$/" }
     ]
    },
    {
     "alias": "generetion_rate $tag_ip_port",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "ip_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "select": [
      [
       { "params": [ "sample_generation_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip_port", "operator": "=~", "value": "/^$ip_port$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU与显存使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "mem_rate $tag_ip_port",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "select": [
      [
       { "params": [ "mem_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip_port", "operator": "=~", "value": "/^$ip_port$/" }
     ]
    },
    {
     "alias": "use_rate $tag_ip_port",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gpu_ip_info",
     "select": [
      [
       { "params": [ "use_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip_port", "operator": "=~", "value": "/^$ip_port$/" }
     ]
    }
   ]
  }
 ]
}